DROP TABLE IF EXISTS PRODUCT; 
CREATE TABLE PRODUCT (  
Id VARCHAR(60) PRIMARY KEY,  
NAME VARCHAR(254),  
Category VARCHAR(30) NOT NULL,
Price NUMERIC(17,6) NOT NULL,
Stock_Quantity NUMERIC(11,4)
); 
ALTER TABLE product ADD COLUMN dtype VARCHAR(255);